# Generated by Django 3.2.9 on 2022-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'registrar'), ('2', 'faculty')], max_length=25, null=True),
        ),
    ]
