# Generated by Django 3.2.6 on 2021-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiletoAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.CharField(help_text='enter file name', max_length=100)),
                ('File', models.FileField(help_text='upload file in csv format', upload_to='')),
            ],
        ),
    ]
