# Generated by Django 3.2.9 on 2022-07-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Actual_file',
            field=models.FileField(help_text='upload file in csv format', upload_to='uploads'),
        ),
    ]
