# Generated by Django 3.2.6 on 2021-09-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_filetoanalyse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiletoAnalyse',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='File',
            new_name='Actual_file',
        ),
    ]
