# Generated by Django 3.2.6 on 2021-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210926_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File_name',
            field=models.CharField(help_text='enter file name', max_length=100, unique=True),
        ),
    ]
