# Generated by Django 3.2.6 on 2021-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Actual_file',
            field=models.FileField(help_text='upload file in csv format', upload_to='uploads/'),
        ),
    ]
