# Generated by Django 3.2.6 on 2021-09-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_file_actual_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Actual_file',
            field=models.FileField(help_text='upload file in csv format', upload_to='app/uploads/'),
        ),
    ]
